name: test-actions
on: [push, pull_request]

jobs:
  test:
    container:
      image: mcr.microsoft.com/playwright:v1.38.0-jammy
    env:
      NO_COVERAGE_BADGE_UPDATE: 1
      FLAGS: FETCH_SERVICE_DISABLE,POST_CONFIGURE_TEST,CONTINUE_ON_ERROR
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - uses: denoland/setup-deno@v1
        with:
          deno-version: 'v1.x'
      - uses: antongolub/action-setup-bun@v1
      - run: |
          yarn remove wpt
          yarn install
      - run: yarn build
      # yarn coverage === c8 + yarn test
      - run: yarn coverage
      - run: yarn test:deno
      - run: yarn test:bun
